#! /bin/bash

if [ "$1" == "jsc" ]; then
  echo "Running JSC (NO JIT) Tests"
  time /System/Library/Frameworks/JavaScriptCore.framework/Versions/Current/Resources/jsc --useJIT=false -e "console = {log:print}; process = {argv: [0, 'a.out']}; " -f ./_build/default/src/layout-test-fixed-encoding/LayoutTestFixedEncoding.bc.js
  exit 0
fi

if [ "$1" == "v8" ]; then
  echo "Running V8 Tests"
  time node ./_build/default/src/layout-test-fixed-encoding/LayoutTestFixedEncoding.bc.js
  exit 0
fi

if [ "$1" == "jscWithJit" ]; then
  echo "Running JSC+JIT Tests"
  time /System/Library/Frameworks/JavaScriptCore.framework/Versions/Current/Resources/jsc --useJIT=true -e "console = {log:print}; process = {argv: [0, 'a.out']}; " -f ./_build/default/src/layout-test-fixed-encoding/LayoutTestFixedEncoding.bc.js
  exit 0
fi

if [ "$1" == "byte" ]; then
  echo "Running Byte Code Tests"
  time ./_build/default/src/layout-test-fixed-encoding/LayoutTestFixedEncoding.bc
  exit 0
fi

echo "Running Native Tests"
time ./_build/default/src/layout-test-fixed-encoding/LayoutTestFixedEncoding.exe
